import Head from "next/head";
import { Box, createStyles } from "@mantine/core";
import { Hero, TopHeader, ProductForm } from "@components";

const useStyles = createStyles((theme) => ({
  section: {
    // 2 equal max sized columns
  },
}));

export default function Home() {
  const { classes } = useStyles();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <TopHeader
          links={[
            { link: "#", label: "Home" },
            { link: "#", label: "Features" },
            { link: "#", label: "Pricing" },
          ]}
        />
      </nav>

      <main>
        <section>
          <Hero />
        </section>

        <section>
          <Box className={classes.section}>
            <ProductForm />
            {/* right column has a title and a paragraph */}
            <Box>
              <h1>title</h1>
              <p>paragraph</p>
            </Box>
          </Box>
        </section>
      </main>
    </>
  );
}
